apiVersion: apps/v1
kind: Deployment
metadata:
  name: staking-core
  namespace: codefresh
  labels:
    app: staking-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staking-core
  template:
    metadata:
      labels:
        app: staking-core
    spec:
      containers:
        - name: staking-core
          image: villenneve/staking-core:musl
          ports:
            - containerPort: 8080
